#!/usr/bin/env bash
# localhost resolves to 127.0.0.2 / facebook.com resolves to 8.8.8.8
cp /etc/hosts /etc/hosts.bak
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts